#Login Page Locators
Input_UserName = "name:loginEmail"
Input_Password = "name:password"
Click_Button = "xpath://button[@type='submit']"
Successfull_msg  = "//span[@class='mr-2']"
#User Management
UserManagement  = "xpath://span[text()='User Management']"
ADD_user = "xpath:(//span[text()='Add'])[1]"
ADD_title = "xpath://h1[text()='Add New User']"
Input_Name = "id:name"
Input_address = "id:address"
Input_Number = "id:phoneNumber"
Click_country_field = "xpath:(//div[@class='select__input-container css-ackcql'])[1]"
Input_country = "(//input[@class='select__input'])[1]"
Selected_country = "xpath://div[text()='Afghanistan']"
Input_state = "(//input[@class='select__input'])[2]"
Selected_state = "xpath:(//div[text()='Balkh'])[1]"
Input_city = "(//input[@class='select__input'])[3]"
Selected_city = "xpath:(//div[text()='Balkh'])[2]"
Input_Email = "xpath://input[@name='email']"
ChooseImage = "id:image"
ImageLocation = "C:/Users/Yash Raj singh/Downloads/download2121.png"
Click_submit = "xpath://button[text()='Submit']"
User_List = "xpath:(//span[text()='List'])[1]"
User_management_title = " //span[text()='User Management']"
Input_search = "id:search-input"
ClickUpdateAction = "xpath://*[local-name()='svg']//*[local-name()='path' and @d='M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z']"
InputEmail_clear = "id:email"
click_Update = "xpath://button[text()='Update']"
Element_contain = "//div[contains(text(),'yash')]"

Element_value = "//div[text()='yash9042@yopmail.com']"
#property management
Property_management = "xpath://span[text()='Property Management']"
property_add = "xpath:(//span[text()='Add'])[2]"
input_propertyName = "name:propertyName"
